### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/server#1]
The server is rejecting new users from logging in. (Image taken while talking to a colleague, appeared after connecting GitHub to server.counterexamples.info.)

![screenshot from 2019-01-11 13-28-30](https://user-images.githubusercontent.com/1559632/51055216-d68e9880-15a4-11e9-907e-b3516f93009b.png)

**Comment by jamesdabbs** [comment]
The auth system has been replaced since this was taken, so I'm assuming it's out of date. Please re-open if you have any other troubles logging in though.
