### ISSUE TITLE
Pushing to production

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/server#12]
In Slack, @jamesdabbs reported that he pushed to production via `yarn run deploy:production`, but the production site seems to be running an earlier commit.

**Comment by jamesdabbs** [comment]
I think what happened here was that I deployed from my local machine without pulling first, so was deploying a commit with my changes, but without everything that was on master.

I'm not _100_ percent sure what made you say that we were running an earlier commit though, so I'm assigning this back to verify. Let me know if anything still looks off?

**Comment by StevenClontz** [comment]
Looks updated now. Last I checked production didn't have any of my commits beyond the space filling curve background, but now I'm seeing the branch management updates, including your fix for unauthenticated users.
