### ISSUE TITLE
Cardinality at most beth 2

### ISSUE THREAD

**Issue by tomaszrz1** [pi-base/server#19]
You cannot search for spaces of cardinality $\leq 2^{2^{\aleph_0}}$. If you try, it matches spaces of cardinality $< 2^{\aleph_0}$ instead.

**Comment by jamesdabbs** [comment]
Sorry, this issue fell through the cracks somewhere. We _just_ launched a new version of the [viewer](https://github.com/pi-base/viewer) at https://topology.pi-base.org, and have [this issue](https://github.com/pi-base/core/issues/9) on the backlog to add better support for cardinal-valued properties.
