### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by diracdeltafunk** [pi-base/server#20]
Not sure if this is the right place to post this, but https://topology.pi-base.org/ is not working. The front page loads fine, but if you try to do anything else, the site just hangs with a "loading" message (see attached image).

![Annotation 2020-05-16 153628](https://user-images.githubusercontent.com/1844060/82131558-3f82b380-978b-11ea-9b4c-ef99ed3b0192.png)

Steps to reproduce:

1. Navigate to https://topology.pi-base.org/ in any web browser.
2. Click "Spaces" in the top menu.

**Comment by jamesdabbs** [comment]
Thanks for the report! It looks like backend certs expired while nobody was watching. 😞 

We _just_ launched a re-written version of the [https://github.com/pi-base/viewer](https://github.com/pi-base/viewer/issues/41) at https://topology.pi-base.org. We're doing some final testing on that, but should be up now and available for use. Please try it out and let us know if you run into any issues.
